# Generated by Django 6.0.6 on 2026-07-02 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('business_health', 'Business Health'), ('safety_incidents', 'Safety Incidents'), ('revenue_churn', 'Revenue & Churn'), ('driver_performance', 'Driver Performance')], max_length=30, unique=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to receive this report.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_children', models.PositiveSmallIntegerField(default=1, help_text='Number of children covered by this plan.')),
                ('priority_matching', models.BooleanField(default=False, help_text='Whether this plan gets priority driver matching.')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings displayed in-app.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('trial', 'Trial')], default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.parent')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('payment_type', models.CharField(choices=[('monthly_sub', 'Monthly Subscription'), ('emergency', 'Emergency Ride'), ('top_up', 'Wallet Top Up'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Wallet')], max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='Payment gateway reference (Paystack, Flutterwave, etc.)', max_length=200, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.parent')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credits', models.PositiveSmallIntegerField(help_text='Number of emergency ride credits purchased')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_topups', to='accounts.parent')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_topup', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Wallet Top-Up',
                'verbose_name_plural': 'Wallet Top-Ups',
            },
        ),
    ]
