# Generated by Django 6.0.6 on 2026-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('panic_alert', 'Panic Alert'), ('late_pickup', 'Late Pickup'), ('sick_child', 'Sick Child'), ('route_deviation', 'Route Deviation'), ('no_show', 'No Show'), ('other', 'Other')], max_length=30),
        ),
    ]
