# Generated by Django 5.2 on 2026-07-03 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_device_model'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profiles', to='zones.zone'),
        ),
        migrations.AddField(
            model_name='parent',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profiles', to='zones.zone'),
        ),
    ]
