# Generated by Django 6.0.6 on 2026-07-04 17:46

import main.gis_fallback
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_point',
            field=main.gis_fallback.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
