# Generated by Django 5.2 on 2026-07-06 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driver_last_point_driver_last_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by_name', models.CharField(blank=True, max_length=120)),
                ('target_user_id', models.BigIntegerField()),
                ('target_role', models.CharField(max_length=10)),
                ('target_full_name', models.CharField(blank=True, max_length=120)),
                ('target_phone', models.CharField(blank=True, max_length=20)),
                ('children_deleted', models.PositiveIntegerField(default=0)),
                ('trips_deleted', models.PositiveIntegerField(default=0)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deletions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
