# Generated by Django 5.2 on 2026-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accountdeletionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='doc_type',
            field=models.CharField(choices=[('LICENSE', "Driver's licence"), ('INSPECTION', 'Vehicle inspection report'), ('BACKGROUND', 'Criminal background check'), ('INSURANCE', 'Vehicle insurance')], max_length=12),
        ),
    ]
