# Generated by Django 5.2 on 2026-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nin_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='doc_type',
            field=models.CharField(choices=[('LICENSE', "Driver's licence"), ('INSPECTION', 'Vehicle inspection report'), ('BACKGROUND', 'Criminal background check'), ('INSURANCE', 'Vehicle insurance'), ('NIN_FRONT', 'National ID (front)'), ('NIN_BACK', 'National ID (back)')], max_length=12),
        ),
    ]
