# Generated by Django 5.2 on 2026-07-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_nin_number_and_more'),
        ('trips', '0005_alter_assignment_driver_alter_stop_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trips.stop'),
        ),
    ]
