# Generated by Django 6.0.6 on 2026-07-02 17:18

import django.db.models.deletion
import main.gis_fallback
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', main.gis_fallback.PointField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('blood_type', models.CharField(blank=True, max_length=3)),
                ('class_name', models.CharField(blank=True, max_length=40)),
                ('allergies', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='children/')),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_point', main.gis_fallback.PointField()),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='children.school')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('morning_time', models.TimeField()),
                ('afternoon_time', models.TimeField()),
                ('days', main.gis_fallback.ArrayField(default=list)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='children.child')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['parent', 'is_active'], name='children_ch_parent__65b233_idx'),
        ),
    ]
