# Generated by Django 5.2 on 2026-07-03 19:38

from main.gis_fallback import PointField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='pickup_point',
            field=PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=PointField(geography=True, srid=4326),
        ),
    ]
