# Generated by Django 5.2 on 2026-07-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_alter_child_pickup_point_alter_school_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
