# Generated by Django 5.2 on 2026-07-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_alter_child_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('ELECTRIC_CAR', 'Electric Car'), ('BODA_BODA', 'Boda Boda')], max_length=20),
        ),
    ]
