# Generated by Django 6.0.6 on 2026-07-02 17:18

import django.db.models.deletion
import main.gis_fallback
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to='accounts.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('direction', models.CharField(choices=[('TO_SCHOOL', 'Home to school'), ('TO_HOME', 'School to home')], max_length=9)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=11)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='accounts.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('NEXT', 'Next stop'), ('PICKED_UP', 'Picked up'), ('DROPPED', 'Dropped off'), ('NO_SHOW', 'No show')], default='UPCOMING', max_length=9)),
                ('eta', models.TimeField(blank=True, null=True)),
                ('picked_point', main.gis_fallback.PointField(blank=True, null=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_point', main.gis_fallback.PointField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='children.child')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.driver')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.parent')),
            ],
            options={
                'indexes': [models.Index(fields=['driver', 'is_active'], name='trips_assig_driver__8d551e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('parent',), name='one_active_driver_per_parent')],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['service_date', 'status'], name='trips_trip_service_cde529_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'service_date'], name='trips_trip_driver__54c8fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('driver', 'service_date', 'direction'), name='one_trip_per_driver_date_direction'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('trip', 'child'), name='child_once_per_trip'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_sequence_per_trip'),
        ),
    ]
