# Generated by Django 5.2 on 2026-07-03 19:38

from main.gis_fallback import PointField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='dropped_point',
            field=PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='stop',
            name='picked_point',
            field=PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
