# Generated by Django 6.0.6 on 2026-07-05 07:51

import django.db.models.deletion
import main.gis_fallback
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driver_last_point_driver_last_seen_at'),
        ('trips', '0002_alter_stop_dropped_point_alter_stop_picked_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', main.gis_fallback.PointField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='accounts.driver')),
            ],
            options={
                'indexes': [models.Index(fields=['driver', 'created_at'], name='trips_locat_driver__c774e0_idx')],
            },
        ),
    ]
