# Generated by Django 5.2 on 2026-07-05 13:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_locationping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationping',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
