# Generated by Django 5.2 on 2026-07-06 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accountdeletionlog'),
        ('children', '0002_alter_child_pickup_point_alter_school_location'),
        ('trips', '0004_alter_locationping_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.driver'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='children.child'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='accounts.driver'),
        ),
    ]
